name: frontend
description: "ABHAYA — Zero-touch autonomous safety guardian for women."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_svg: ^2.0.17

  # State Management
  provider: ^6.1.5

  # Navigation
  go_router: ^16.0.0

  # Networking
  http: ^1.5.0
  dio: ^5.8.0
  web_socket_channel: ^3.0.3

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5

  # Location & Maps
  geolocator: ^14.0.0

  # Sensors & AI
  sensors_plus: ^7.0.1
  tflite_flutter: ^0.11.0

  # Audio & Camera
  record: ^6.2.1
  camera: ^0.11.1

  # Notifications
  flutter_local_notifications: ^19.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5

  # Permissions
  permission_handler: ^12.0.0

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.2
  image_picker: ^1.1.2
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  flutter_phone_direct_caller: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ABHAY.png"
  adaptive_icon_background: "#EAE7E1"
  adaptive_icon_foreground: "assets/ABHAY.png"

flutter:
  uses-material-design: true
  assets:
    - assets/ABHAY.png
